// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"2025-Lush-and-Verdant-Backend/config"
	"2025-Lush-and-Verdant-Backend/controller"
	"2025-Lush-and-Verdant-Backend/dao"
	"2025-Lush-and-Verdant-Backend/route"
	"2025-Lush-and-Verdant-Backend/service"
	"log"
)

// Injectors from main.go:

func InitializeApp() (*route.App, error) {
	string2 := _wireStringValue
	db := dao.NewDB(string2)
	userService := service.NewUserService(db)
	userController := controller.NewUserController(userService)
	userSvc := route.NewUserSvc(userController)
	sloganService := service.NewSloganService(db)
	sloganController := controller.NewSloganController(sloganService)
	sloganSvc := route.NewSloganSvc(sloganController)
	goalService := service.NewGoalService(db)
	goalController := controller.NewGoalController(goalService)
	goalSvc := route.NewGoalSvc(goalController)
	app := route.NewApp(userSvc, sloganSvc, goalSvc)
	return app, nil
}

var (
	_wireStringValue = config.Dsn
)

// main.go:

func main() {
	app, err := InitializeApp()
	if err != nil {
		log.Fatal(err)
	}
	app.Run()
}
