definitions:
  main.AlterPassword:
    properties:
      code:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  main.CancelUser:
    properties:
      email:
        type: string
    type: object
  main.Email:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  main.Response:
    properties:
      error:
        type: string
      message:
        type: string
      token:
        type: string
    type: object
  main.UserLogin:
    properties:
      code:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  main.UserRegister:
    properties:
      code:
        type: string
      device_num:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  main.VisterLogin:
    properties:
      device_num:
        type: string
      email:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /alter/password:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱和验证码修改密码，验证码有效后可以修改密码。
      parameters:
      - description: 修改密码信息
        in: body
        name: alter
        required: true
        schema:
          $ref: '#/definitions/main.AlterPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 忘记密码和修改密码
      tags:
      - 用户相关
  /cancel/account:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱注销账户。如果邮箱对应的用户不存在，返回错误信息。
      parameters:
      - description: 注销账户信息
        in: body
        name: cancel
        required: true
        schema:
          $ref: '#/definitions/main.CancelUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 注销账户
      tags:
      - 用户相关
  /login/password:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱和密码进行登录，成功后返回token
      parameters:
      - description: 用户登录信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 用户登录（密码方式）
      tags:
      - 用户相关
  /login/visitor:
    post:
      consumes:
      - application/json
      description: 游客通过设备号进行登录，如果该设备号尚未注册，则会创建一个新用户并返回 JWT Token
      parameters:
      - description: 游客登录信息
        in: body
        name: vister
        required: true
        schema:
          $ref: '#/definitions/main.VisterLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 游客登录
      tags:
      - 用户相关
  /register:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱注册，包含验证码验证
      parameters:
      - description: 用户注册信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 用户注册
      tags:
      - 用户相关
  /send-email:
    post:
      consumes:
      - application/json
      description: 向用户邮箱发送验证码
      parameters:
      - description: 邮箱发送验证码信息
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/main.Email'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 发送验证码邮件
      tags:
      - 邮件相关
swagger: "2.0"
