definitions:
  main.AlterPassword:
    properties:
      code:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  main.CancelUser:
    properties:
      email:
        type: string
    type: object
  main.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  main.Newslogan:
    properties:
      id:
        type: integer
      newslogan:
        type: string
    type: object
  main.Response:
    properties:
      error:
        type: string
      message:
        type: string
      token:
        type: string
    type: object
  main.Useemail:
    properties:
      email_name:
        type: string
    type: object
  main.UserRegister:
    properties:
      code:
        type: string
      device_num:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  main.VLogin:
    properties:
      device_num:
        type: string
    type: object
info:
  contact: {}
paths:
  /courage_words/change_word:
    put:
      consumes:
      - application/json
      description: 用户可以通过此接口更新他们的口号
      parameters:
      - description: 新的口号内容
        in: body
        name: newSlogan
        required: true
        schema:
          $ref: '#/definitions/main.Newslogan'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                message:
                  type: string
              type: object
        "400":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                error:
                  type: string
              type: object
        "404":
          description: 未找到
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: 服务器错误
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                error:
                  type: string
              type: object
      security:
      - BearerAuth: []
      summary: 更新用户的口号
      tags:
      - 用户
  /courage_words/get_word/{device}:
    get:
      consumes:
      - application/json
      description: 通过设备号获取激励语，如果设备尚未设置激励语，则为其分配一个
      parameters:
      - description: 设备号
        in: path
        name: device
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                message:
                  type: string
              type: object
        "400":
          description: 设备号不能为空
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                error:
                  type: string
              type: object
        "404":
          description: 未找到激励语
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                error:
                  type: string
              type: object
        "409":
          description: 已拥有激励语
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                message:
                  type: string
              type: object
        "500":
          description: 服务器错误
          schema:
            allOf:
            - $ref: '#/definitions/main.Response'
            - properties:
                error:
                  type: string
              type: object
      summary: 获取设备的激励语
      tags:
      - 用户
  /user/cancel:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱注销账户。如果邮箱对应的用户不存在，返回错误信息。
      parameters:
      - description: 注销账户信息
        in: body
        name: cancel
        required: true
        schema:
          $ref: '#/definitions/main.CancelUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 注销账户
      tags:
      - 用户相关
  /user/login/forget_alter:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱和验证码修改密码，验证码有效后可以修改密码。
      parameters:
      - description: 修改密码信息
        in: body
        name: alter
        required: true
        schema:
          $ref: '#/definitions/main.AlterPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 忘记密码和修改密码
      tags:
      - 用户相关
  /user/login_p:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱和密码进行登录，成功后返回token
      parameters:
      - description: 用户登录信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 用户登录（密码方式）
      tags:
      - 用户相关
  /user/login_v:
    post:
      consumes:
      - application/json
      description: 游客通过设备号进行登录，如果该设备号尚未注册，则会创建一个新用户并返回 JWT Token
      parameters:
      - description: 游客登录信息
        in: body
        name: vister
        required: true
        schema:
          $ref: '#/definitions/main.VLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 游客登录
      tags:
      - 用户相关
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱注册，包含验证码验证
      parameters:
      - description: 用户注册信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 用户注册
      tags:
      - 用户相关
  /user/send_email:
    post:
      consumes:
      - application/json
      description: 向用户邮箱发送验证码
      parameters:
      - description: 邮箱发送验证码信息
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/main.Useemail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
      summary: 发送验证码邮件
      tags:
      - 邮件相关
swagger: "2.0"
